enabled = true

# Rosto
[[translation]]
old = "Silver Rimless Glasses"
new = "Óculos Sem Aro Prata"

[[translation]]
old = "Red Rimless Glasses"
new = "Óculos Sem Aro Vermelho"

[[translation]]
old = "Silver Half-Rim Glasses"
new = "Óculos Meio Aro Prata"

[[translation]]
old = "Brown Half-Rim Glasses"
new = "Óculos Meio Aro Marrom"

[[translation]]
old = "Orange Frame Glasses"
new = "Óculos Aro Cheio Laranja"

[[translation]]
old = "Black Frame Glasses"
new = "Óculos Aro Cheio Preto"

[[translation]]
old = "Blue Under-Rim Glasses"
new = "Óculos Meio Aro Inferior Azul"

[[translation]]
old = "Pink Under-Rim Glasses"
new = "Óculos Meio Aro Inferior Rosa"

[[translation]]
old = "Swirly Glasses"
new = "Óculos com Espirais"

[[translation]]
old = "Black Pointed Glasses"
new = "Óculos Pontudo Preto"

[[translation]]
old = "Red Pointed Glasses"
new = "Óculos Pontudo Vermelho"

[[translation]]
old = "Sunglasses"
new = "Óculos de Sol"

[[translation]]
old = "Goggles"
new = "Óculos de Proteção"

[[translation]]
old = "Cyber Visor"
new = "Ciber-Visor"

[[translation]]
old = "Monocle"
new = "Monóculo"

[[translation]]
old = "Eye Mask"
new = "Máscara de Dormir"

[[translation]]
old = "Anime Eye Mask"
new = "Máscara Anime de Dormir"

[[translation]]
old = "Black Eyepatch"
new = "Tapa-Olho Preto"

[[translation]]
old = "Green Eyepatch"
new = "Tapa-Olho Verde"

[[translation]]
old = "Yellow Eyepatch"
new = "Tapa-Olho Amarelo"

[[translation]]
old = "Orange Eyepatch"
new = "Tapa-Olho Laranja"

[[translation]]
old = "Pink Eyepatch"
new = "Tapa-Olho Rosa"

[[translation]]
old = "Blue Eyepatch"
new = "Tapa-Olho Azul"

[[translation]]
old = "Red Eyepatch"
new = "Tapa-Olho Vermelho"

[[translation]]
old = "White Eyepatch"
new = "Tapa-Olho Branco"

[[translation]]
old = "Blue Chinese Opera Mask"
new = "Máscara de Ópera Chinesa Azul"

[[translation]]
old = "Red Chinese Opera Mask"
new = "Máscara de Ópera Chinesa Vermelha"

[[translation]]
old = "Butterfly Mask"
new = "Máscara de Borboleta"

[[translation]]
old = "Masquerade Mask"
new = "Máscara de Baile"

[[translation]]
old = "Gas Mask"
new = "Máscara de Gás"

[[translation]]
old = "Noh Mask (Demon)"
new = "Máscara Noh (Demônio)"

[[translation]]
old = "Noh Mask (Woman)"
new = "Máscara Noh (Senhora)"

[[translation]]
old = "Noh Mask (Old Man)"
new = "Máscara Noh (Senhor)"

[[translation]]
old = "White Mask"
new = "Máscara Branca"

[[translation]]
old = "White Mask (with Tongue)"
new = "Máscara Branca (com Linguinha)"

[[translation]]
old = "White Mask (ω)"
new = "Máscara Branca (三 ω 三)"

[[translation]]
old = "White Mask (ε)"
new = "Máscara Branca ( ε )"

[[translation]]
old = "Cat Whiskers"
new = "Bigodes de Gato"

[[translation]]
old = "Oversized Glasses"
new = "ÓcuZÃO"

[[translation]]
old = "Fake Mustache"
new = "Bigode Falso"

[[translation]]
old = "Beak"
new = "Bico"

[[translation]]
old = "Anonymizer"
new = "\"Sou Anonimizador A\""

[[translation]]
old = "Chic Indigo Glasses"
new = "Óculos Índigo Chique"

[[translation]]
old = "Chic Purple Glasses"
new = "Óculos Roxo Chique"

[[translation]]
old = "Silver Round Glasses"
new = "Óculos Redondo Prata"

[[translation]]
old = "Brown Round Glasses"
new = "Óculos Redondo Marrom"

[[translation]]
old = "Comic Eye Mask"
new = "Máscara Quadrinho de Dormir"

[[translation]]
old = "Chic Sunglasses"
new = "Óculos de Sol Chique"

[[translation]]
old = "Swimming Goggles"
new = "Óculos de Natação"

[[translation]]
old = "Gag Glasses"
new = "Óculos de Disfarce"

[[translation]]
old = "Clown Nose"
new = "Nariz de Palhaço"

[[translation]]
old = "Fox Mask"
new = "Máscara de Raposa"

# Cabeça
[[translation]]
old = "Halo"
new = "Auréola"

[[translation]]
old = "Chicks"
new = "Três Patinhos Foram Rodar"

[[translation]]
old = "Nurse's Cap"
new = "Chapéu de Enfermeira"

[[translation]]
old = "Maid's Headband"
new = "Tiara de Empregada"

[[translation]]
old = "Black Cat Ears"
new = "Orelhas de Gato Preto"

[[translation]]
old = "White Cat Ears"
new = "Orelhas de Gato Branco"

[[translation]]
old = "Brown Cat Ears"
new = "Orelhas de Gato Marrom"

[[translation]]
old = "Black Rabbit Ears"
new = "Orelhas de Coelho Preto"

[[translation]]
old = "White Rabbit Ears"
new = "Orelhas de Coelho Branco"

[[translation]]
old = "Pink Rabbit Ears"
new = "Orelhas de Coelho Rosa"

[[translation]]
old = "Oni Horn"
new = "Chifre de Oni"

[[translation]]
old = "Devil Horns"
new = "Chifres de Demônio"

[[translation]]
old = "Green Cowlick A"
new = "Ahoge Verde A"

[[translation]]
old = "Yellow Cowlick B"
new = "Ahoge Amarelo B"

[[translation]]
old = "Yellow Cowlick C"
new = "Ahoge Amarelo C"

[[translation]]
old = "Pink Cowlick D"
new = "Ahoge Rosa D"

[[translation]]
old = "Blue Cowlick E"
new = "Ahoge Azul E"

[[translation]]
old = "Brown Cowlick F"
new = "Ahoge Marrom F"

[[translation]]
old = "Sweat Drops (Right)"
new = "Gotas de Suor (Direita)"

[[translation]]
old = "Sweat Drops (Left)"
new = "Gotas de Suor (Esquerda)"

[[translation]]
old = "Red Puyo Cap"
new = "Chapéu de Puyo Vermelho"

[[translation]]
old = "Green Puyo Barrette"
new = "Presilha de Puyo Verde"

[[translation]]
old = "Golden Crown"
new = "Coroa Dourada"

[[translation]]
old = "Platinum Crown"
new = "Coroa Platinada"

[[translation]]
old = "Mini Silk Hat"
new = "Mini Chapéu de Seda"

[[translation]]
old = "Chef's Hat"
new = "Chapéu de Chef"

[[translation]]
old = "Yellow Cowlick A"
new = "Ahoge Amarelo A"

[[translation]]
old = "Pink Cowlick A"
new = "Ahoge Rosa A"

[[translation]]
old = "Blue Cowlick A"
new = "Ahoge Azul A"

[[translation]]
old = "Brown Cowlick A"
new = "Ahoge Marrom A"

[[translation]]
old = "Gold Cowlick A"
new = "Ahoge Dourado A"

[[translation]]
old = "Silver Cowlick A"
new = "Ahoge Prata A"

[[translation]]
old = "Light Brown Cowlick A"
new = "Ahoge Marrom Claro A"

[[translation]]
old = "Red Cowlick A"
new = "Ahoge Vermelho A"

[[translation]]
old = "Green Cowlick B"
new = "Ahoge Verde B"

[[translation]]
old = "Pink Cowlick B"
new = "Ahoge Rosa B"

[[translation]]
old = "Blue Cowlick B"
new = "Ahoge Azul B"

[[translation]]
old = "Brown Cowlick B"
new = "Ahoge Marrom B"

[[translation]]
old = "Gold Cowlick B"
new = "Ahoge Dourado B"

[[translation]]
old = "Silver Cowlick B"
new = "Ahoge Prata B"

[[translation]]
old = "Light Brown Cowlick B"
new = "Ahoge Marrom Claro B"

[[translation]]
old = "Red Cowlick B"
new = "Ahoge Vermelho B"

[[translation]]
old = "Green Cowlick C"
new = "Ahoge Verde C"

[[translation]]
old = "Pink Cowlick C"
new = "Ahoge Rosa C"

[[translation]]
old = "Blue Cowlick C"
new = "Ahoge Azul C"

[[translation]]
old = "Brown Cowlick C"
new = "Ahoge Marrom C"

[[translation]]
old = "Gold Cowlick C"
new = "Ahoge Dourado C"

[[translation]]
old = "Silver Cowlick C"
new = "Ahoge Prata C"

[[translation]]
old = "Light Brown Cowlick C"
new = "Ahoge Marrom Claro C"

[[translation]]
old = "Red Cowlick C"
new = "Ahoge Vermelho C"

[[translation]]
old = "Green Cowlick D"
new = "Ahoge Verde D"

[[translation]]
old = "Yellow Cowlick D"
new = "Ahoge Amarelo D"

[[translation]]
old = "Blue Cowlick D"
new = "Ahoge Azul D"

[[translation]]
old = "Brown Cowlick D"
new = "Ahoge Marrom D"

[[translation]]
old = "Gold Cowlick D"
new = "Ahoge Dourado D"

[[translation]]
old = "Silver Cowlick D"
new = "Ahoge Prata D"

[[translation]]
old = "Light Brown Cowlick D"
new = "Ahoge Marrom Claro D"

[[translation]]
old = "Red Cowlick D"
new = "Ahoge Vermelho D"

[[translation]]
old = "Green Cowlick E"
new = "Ahoge Verde E"

[[translation]]
old = "Yellow Cowlick E"
new = "Ahoge Amarelo E"

[[translation]]
old = "Pink Cowlick E"
new = "Ahoge Rosa E"

[[translation]]
old = "Brown Cowlick E"
new = "Ahoge Marrom E"

[[translation]]
old = "Gold Cowlick E"
new = "Ahoge Dourado E"

[[translation]]
old = "Silver Cowlick E"
new = "Ahoge Prata E"

[[translation]]
old = "Light Brown Cowlick E"
new = "Ahoge Marrom Claro E"

[[translation]]
old = "Red Cowlick E"
new = "Ahoge Vermelho E"

[[translation]]
old = "Green Cowlick F"
new = "Ahoge Verde F"

[[translation]]
old = "Yellow Cowlick F"
new = "Ahoge Amarelo F"

[[translation]]
old = "Pink Cowlick F"
new = "Ahoge Rosa F"

[[translation]]
old = "Blue Cowlick F"
new = "Ahoge Azul F"

[[translation]]
old = "Gold Cowlick F"
new = "Ahoge Dourado F"

[[translation]]
old = "Silver Cowlick F"
new = "Ahoge Prata F"

[[translation]]
old = "Light Brown Cowlick F"
new = "Ahoge Marrom Claro F"

[[translation]]
old = "Red Cowlick F"
new = "Ahoge Vermelho F"

[[translation]]
old = "Dog Ears"
new = "Orelhas de Cachorro"

[[translation]]
old = "Ram Horns"
new = "Chifres de Carneiro"

[[translation]]
old = "Devil's Head Wings"
new = "Asas de Demônio na Cabeça"

[[translation]]
old = "Bird's Nest"
new = "Ninho de Pássaro"

[[translation]]
old = "Yurei Headband"
new = "Bandana de Yurei"

[[translation]]
old = "Satellite Dish"
new = "Antena Parabólica"

[[translation]]
old = "Red Party Hat"
new = "Chapéu de Festa Vermelho"

[[translation]]
old = "Blue Party Hat"
new = "Chapéu de Festa Azul"

[[translation]]
old = "Yellow Party Hat"
new = "Chapéu de Festa Amarelo"

[[translation]]
old = "Great White Shark"
new = "Tubarão-branco"

[[translation]]
old = "Pumpkin Head"
new = "Cabeça de Abóbora"

[[translation]]
old = "Snowman Head"
new = "Cabeça de Boneco de Neve ( ● _ ● )"

[[translation]]
old = "Smiling Snowman Head"
new = "Cabeça de Boneco de Neve ( ● ω ● )"

[[translation]]
old = "Overhead Heart"
new = "Coração ao Ar"

[[translation]]
old = "Steaming Mad"
new = "Muito ÓDIO"

# Torso
[[translation]]
old = "Gold Bow Tie"
new = "Gravata-borboleta Dourada"

[[translation]]
old = "Black Bow Tie"
new = "Gravata-borboleta Preta"

[[translation]]
old = "Red Bow Tie"
new = "Gravata-borboleta Vermelha"

[[translation]]
old = "Blue Ribbon"
new = "Laço Azul"

[[translation]]
old = "Yellow Ribbon"
new = "Laço Amarelo"

[[translation]]
old = "Pink Ribbon"
new = "Laço Rosa"

[[translation]]
old = "Gold Bell"
new = "Sino Dourado"

[[translation]]
old = "Silver Bell"
new = "Sino Prateado"

[[translation]]
old = "Badge"
new = "Emblema"

[[translation]]
old = "Detachable Collar"
new = "Gola Removível"

[[translation]]
old = "Harmonica"
new = "Harmónica"

[[translation]]
old = "Gold Medal"
new = "Medalha de Ouro"

[[translation]]
old = "Silver Medal"
new = "Medalha de Prata"

[[translation]]
old = "Bronze Medal"
new = "Medalha de Bronze"

[[translation]]
old = "Green Bib"
new = "Babador Verde"

[[translation]]
old = "Yellow Bib"
new = "Babador Amarelo"

[[translation]]
old = "Orange Bib"
new = "Babador Laranja"

[[translation]]
old = "Pink Bib"
new = "Babador Rosa"

[[translation]]
old = "Blue Bib"
new = "Babador Azul"

[[translation]]
old = "Red Bib"
new = "Babador Vermelho"

[[translation]]
old = "Beginner Badge"
new = "Medalha de Iniciante"

[[translation]]
old = "Green Timer Light"
new = "Luz do Temporizador Verde"

[[translation]]
old = "Red Timer Light"
new = "Luz do Temporizador Vermelha"

[[translation]]
old = "Heart"
new = "Coração"

[[translation]]
old = "Broken Heart"
new = "Coração Partido"

# Costa
[[translation]]
old = "Light Wings"
new = "Asas da Luz"

[[translation]]
old = "Angel Wings"
new = "Asas de Anjo"

[[translation]]
old = "Butterfly Wings"
new = "Asas de Borboleta"

[[translation]]
old = "Devil Wings"
new = "Asas de Demônio"

[[translation]]
old = "Teddy Bear"
new = "Ursinho"

[[translation]]
old = "Backpack"
new = "Mochila"

[[translation]]
old = "Knapsack"
new = "Mochila Simples"

[[translation]]
old = "Black Bookbag"
new = "Randoseru Preta"

[[translation]]
old = "Red Bookbag"
new = "Randoseru Vermelha"

[[translation]]
old = "Jetpack"
new = "Mochila a Jato"

[[translation]]
old = "Black Cat Tail"
new = "Rabo de Gato Preto"

[[translation]]
old = "White Cat Tail"
new = "Rabo de Gato Branco"

[[translation]]
old = "Tiger Cat Tail"
new = "Rabo de Gato-do-mato"

[[translation]]
old = "Black Rabbit Tail"
new = "Rabo de Coelho Preto"

[[translation]]
old = "White Rabbit Tail"
new = "Rabo de Coelho Branco"

[[translation]]
old = "Pink Rabbit Tail"
new = "Rabo de Coelho Rosa"

[[translation]]
old = "Fox Tail"
new = "Rabo de Raposa"

[[translation]]
old = "Devil Tail"
new = "Cauda de Demônio"

[[translation]]
old = "Wind-Up Key"
new = "Chave de Corda"

[[translation]]
old = "Backpack with Posters"
new = "Mochila com Posters"

[[translation]]
old = "Black Bookbag & Recorder"
new = "Randoseru Preta com Flauta Doce"

[[translation]]
old = "Red Bookbag & Recorder"
new = "Randoseru Vermelha com Flauta Doce"

[[translation]]
old = "Mechanical Wings"
new = "Asas Mecânicas"

[[translation]]
old = "Schoolbag"
new = "Maleta Escolar"

[[translation]]
old = "Big Red Button"
new = "Botãozão Vermelho"

[[translation]]
old = "Dog Tail"
new = "Rabo de Cachorro"

[[translation]]
old = "Dinosaur Tail"
new = "Rabo de Dinossauro"

[[translation]]
old = "Nekomata Tails"
new = "Rabo de Nekomata"

[[translation]]
old = "Nine Fox Tails"
new = "Nove Caudas de Raposa"

[[translation]]
old = "Dangling Cat"
new = "Gato Pendurado"