enabled = true

[[translation]]
old = "Breadful T-Shirt"
new = "Camiseta Pãozástica"

[[translation]]
old = "Gutsune Miku"
new = "Hatsune Miudeus"

[[translation]]
old = "Virtual Neon Sign"
new = "Letreiro Virtual Neon"

[[translation]]
old = "Space DIVA"
new = "DIVA Espacial"

[[translation]]
old = "MEGA39's LIVE"
new = "MEGA39's AO VIVO"

[[translation]]
old = "A World Made By 6"
new = "Um Mundo Feito Por 6"

[[translation]]
old = "Orange Float"
new = "Flutuação Laranja"

[[translation]]
old = "Banana Beach"
new = "Praia Banana"

[[translation]]
old = "Marvelous T"
new = "Maravilhoso T"

[[translation]]
old = "I LOVE MEIKO T-Shirt"
new = "Camiseta TE AMO MEIKO"

[[translation]]
old = "Premium T-Shirt H"
new = "Camiseta Premium H"

[[translation]]
old = "Collaboration T-Shirt A"
new = "Camiseta de Colaboração A"

[[translation]]
old = "10th Anniv. T-Shirt (Ittomaru)"
new = "Camiseta de 10º Aniversário (Ittomaru)"

[[translation]]
old = "10th Anniv. T-Shirt (iXima)"
new = "Camiseta de 10º Aniversário (iXima)"

[[translation]]
old = "10th Anniv. T-Shirt (KEI)"
new = "Camiseta de 10º Aniversário (KEI)"

[[translation]]
old = "10th Anniv. T-Shirt (LAM)"
new = "Camiseta de 10º Aniversário (LAM)"

[[translation]]
old = "10th Anniv. T-Shirt (Mago)"
new = "Camiseta de 10º Aniversário (Mago)"

[[translation]]
old = "10th Anniv. T-Shirt (MINAKATALABORATORY)"
new = "Camiseta de 10º Aniversário (MINAKATALABORATORY)"

[[translation]]
old = "10th Anniv. T-Shirt (nezuki)"
new = "Camiseta de 10º Aniversário (nezuki)"

[[translation]]
old = "10th Anniv. T-Shirt (Tama)"
new = "Camiseta de 10º Aniversário (Tama)"

[[translation]]
old = "10th Anniv. T-Shirt (Y Oji)"
new = "Camiseta de 10º Aniversário (Y Oji)"

[[translation]]
old = "Collaboration T-Shirt J"
new = "Camiseta de Colaboração J"

[[translation]]
old = "Premium T-Shirt F"
new = "Camiseta Premium F"

[[translation]]
old = "Premium T-Shirt G"
new = "Camiseta Premium G"

[[translation]]
old = "Premium T-Shirt A"
new = "Camiseta Premium A"

[[translation]]
old = "Custom T-Shirt A"
new = "Camiseta Customizada A"

[[translation]]
old = "Custom T-Shirt B"
new = "Camiseta Customizada B"

[[translation]]
old = "Custom T-Shirt C"
new = "Camiseta Customizada C"

[[translation]]
old = "Custom T-Shirt D"
new = "Camiseta Customizada D"

[[translation]]
old = "Custom T-Shirt E"
new = "Camiseta Customizada E"

[[translation]]
old = "Holy Leek"
new = "Alho-poró Sagrado"

[[translation]]
old = "Rose Record"
new = "Gravação de Rosas"

[[translation]]
old = "Starlight Diva"
new = "Diva Estelar"

[[translation]]
old = "goopy meeku"
new = "gosmikenta"

[[translation]]
old = "Pastel Tee"
new = "Camiseta Pastel"

[[translation]]
old = "Premium T-Shirt K (KEI)"
new = "Camiseta Premium K (KEI)"