enabled = true

# 001 - Love is War
[[translation]]
old = "Love is War"
new = "Love is War (Amor é Guerra)"

# 002 - The World is Mine
[[translation]]
old = "The World is Mine"
new = "The World is Mine (O Mundo é Meu)"

# 005 - Melt
[[translation]]
old = "Melt"
new = "Melt (Derreter)"

# 007 - Strobo Nights
[[translation]]
old = "Strobo Nights"
new = "Strobo Nights (Noites Strobo)"

# 008 - Star Story
[[translation]]
old = "Star Story"
new = "Star Story (História das Estrelas)"

# 013 - Grumpy Waltz
[[translation]]
old = "Grumpy Waltz"
new = "Grumpy Waltz (Valsa Mal-Humorada)"

# 014 - Miracle Paint
[[translation]]
old = "Miracle Paint"
new = "Miracle Paint (Tinta Milagrosa)"

# 016 - VOC@LOID in Love
[[translation]]
old = "VOC@LOID in Love"
new = "VOC@LOID in Love (VOC@LOID Apaixonada)"

# 022 - The secret garden
[[translation]]
old = "The secret garden"
new = "The secret garden (O jardim secreto)"

# 028 - I'll Miku-Miku You♪ (For Reals)
[[translation]]
old = "I'll Miku-Miku You♪ (For Reals)"
new = "I'll Miku-Miku You♪ (For Reals) (Eu vou Miku-Miku Você♪ (É Sério))"

# 030 - Electric Angel
[[translation]]
old = "Electric Angel"
new = "Electric Angel (Anjo Elétrico)"

# 031 - I'm Your Diva
[[translation]]
old = "I'm Your Diva"
new = "I'm Your Diva (Sou Sua Diva)"

# 032 - The Disappearance of Hatsune Miku
[[translation]]
old = "The Disappearance of Hatsune Miku"
new = "The Disappearance of Hatsune Miku (O Desaparecimento de Hatsune Miku)"

# 037 - When First Love Ends
[[translation]]
old = "When First Love Ends"
new = "When First Love Ends (Quando o Primeiro Amor Acaba)"

# 038 - Look This Way, Baby
[[translation]]
old = "Look This Way, Baby"
new = "Look This Way, Baby (Olha Pra Cá, Baby)"

# 039 - Finder (DSLR remix - re:edit)
[[translation]]
old = "Finder (DSLR remix - re:edit)"
new = "Finder (Localizadora) (DSLR remix - re:edit)"

# 040 - Yellow
[[translation]]
old = "Yellow"
new = "Amarelo"

# 041 - Colorful × Melody
[[translation]]
old = "Colorful × Melody"
new = "Colorful × Melody (Melodia × Colorida)"

# 042 - The Intense Voice of Hatsune Miku
[[translation]]
old = "The Intense Voice of Hatsune Miku"
new = "The Intense Voice of Hatsune Miku (A Intensa Voz de Hatsune Miku)"

# 043 - Romeo and Cinderella
[[translation]]
old = "Romeo and Cinderella"
new = "Romeo and Cinderella (Romeo e Cinderela)"

# 044 - Magnet
[[translation]]
old = "Magnet"
new = "Magnet (Ímã)"

# 045 - Dear
[[translation]]
old = "Dear"
new = "Dear (Querido)"

# 046 - from Y to Y
[[translation]]
old = "from Y to Y"
new = "from Y to Y (de Y a Y)"

# 047 - Gemini
[[translation]]
old = "Gemini"
new = "Gemini (Gêmeos)"

# 048 - Aikotoba
[[translation]]
old = "Aikotoba"
new = "Aikotoba (Palavras de Amor)"

# 050 - Saihate
[[translation]]
old = "Saihate"
new = ""

# 051 - VOiCE -DIVA　MIX-
[[translation]]
old = "VOiCE -DIVA　MIX-"
new = ""

# 052 - Love-Colored Ward
[[translation]]
old = "Love-Colored Ward"
new = ""

# 053 - Gigantic Girl
[[translation]]
old = "Gigantic Girl"
new = ""

# 054 - Roshin Yukai
[[translation]]
old = "Roshin Yukai"
new = ""

# 055 - Kokoro
[[translation]]
old = "Kokoro"
new = ""

# 056 - Butterfly on Your Right Shoulder
[[translation]]
old = "Butterfly on Your Right Shoulder"
new = ""

# 057 - Double Lariat
[[translation]]
old = "Double Lariat"
new = ""

# 058 - Cantarella
[[translation]]
old = "Cantarella"
new = ""

# 059 - Change Me
[[translation]]
old = "Change Me"
new = ""

# 060 - Sound
[[translation]]
old = "Sound"
new = ""

# 061 - Clover♣Club
[[translation]]
old = "Clover♣Club"
new = ""

# 062 - Promise
[[translation]]
old = "Promise"
new = ""

# 065 - The First Sound
[[translation]]
old = "The First Sound"
new = ""

# 066 - Just Be Friends
[[translation]]
old = "Just Be Friends"
new = ""

# 068 - Electric Angel
[[translation]]
old = "Electric Angel"
new = ""

# 079 - SPiCa -39's Giving Day Edition-
[[translation]]
old = "SPiCa -39's Giving Day Edition-"
new = ""

# 081 - Though My Song Has No Form
[[translation]]
old = "Though My Song Has No Form"
new = ""

# 082 - Two-Sided Lovers
[[translation]]
old = "Two-Sided Lovers"
new = ""

# 083 - *Hello, Planet.
[[translation]]
old = "*Hello, Planet."
new = ""

# 085 - Solitude's End -extend edition-
[[translation]]
old = "Solitude's End -extend edition-"
new = ""

# 086 - Puzzle
[[translation]]
old = "Puzzle"
new = ""

# 087 - Palette
[[translation]]
old = "Palette"
new = ""

# 088 - Thousand Year Solo (DIVA Edit)
[[translation]]
old = "Thousand Year Solo (DIVA Edit)"
new = ""

# 089 - Lover's Suicide Oblivion
[[translation]]
old = "Lover's Suicide Oblivion"
new = ""

# 090 - Close and Open, Demons and The Dead
[[translation]]
old = "Close and Open, Demons and The Dead"
new = ""

# 091 - Rolling Girl
[[translation]]
old = "Rolling Girl"
new = ""

# 092 - Starduster
[[translation]]
old = "Starduster"
new = ""

# 093 - Paradichlorobenzene
[[translation]]
old = "Paradichlorobenzene"
new = ""

# 094 - Wintry Winds
[[translation]]
old = "Wintry Winds"
new = ""

# 095 - NekoMimi Switch
[[translation]]
old = "NekoMimi Switch"
new = ""

# 096 - Sekiranun Graffiti
[[translation]]
old = "Sekiranun Graffiti"
new = ""

# 097 - RinRin Signal -Append Mix-
[[translation]]
old = "RinRin Signal -Append Mix-"
new = ""

# 102 - Quartet of Multiple Futures -Quartet Theme-
[[translation]]
old = "Quartet of Multiple Futures -Quartet Theme-"
new = ""

# 103 - AFTER BURNER
[[translation]]
old = "AFTER BURNER"
new = ""

# 104 - LIKE THE WIND
[[translation]]
old = "LIKE THE WIND"
new = ""

# 201 - Stardust Utopia
[[translation]]
old = "Stardust Utopia"
new = ""

# 202 - StargazeR
[[translation]]
old = "StargazeR"
new = ""

# 212 - Colorful × Sexy
[[translation]]
old = "Colorful × Sexy"
new = ""

# 213 - Luka Luka ★ Night Fever
[[translation]]
old = "Luka Luka ★ Night Fever"
new = ""

# 215 - Leia
[[translation]]
old = "Leia"
new = ""

# 218 - The Snow White Princess is...
[[translation]]
old = "The Snow White Princess is..."
new = ""

# 219 - Deep Sea Girl
[[translation]]
old = "Deep Sea Girl"
new = ""

# 220 - World's End Dance Hall -Live Dance Edition-
[[translation]]
old = "World's End Dance Hall -Live Dance Edition-"
new = ""

# 221 - NekoMimi Archive
[[translation]]
old = "NekoMimi Archive"
new = ""

# 222 - Black Gold
[[translation]]
old = "Black Gold"
new = ""

# 224 - Rosary Pale
[[translation]]
old = "Rosary Pale"
new = ""

# 225 - Yumeyume
[[translation]]
old = "Yumeyume"
new = ""

# 226 - On The Rocks
[[translation]]
old = "On The Rocks"
new = ""

# 227 - Mousou Sketch
[[translation]]
old = "Mousou Sketch"
new = ""

# 228 - No Logic
[[translation]]
old = "No Logic"
new = ""

# 231 - Kipple Industry Inc.
[[translation]]
old = "Kipple Industry Inc."
new = ""

# 232 - 39
[[translation]]
old = "39"
new = ""

# 234 - Deep Sea City Underground
[[translation]]
old = "Deep Sea City Underground"
new = ""

# 238 - SING&SMILE
[[translation]]
old = "SING&SMILE"
new = ""

# 239 - Tricolore Airline
[[translation]]
old = "Tricolore Airline"
new = ""

# 240 - Systematic Love
[[translation]]
old = "Systematic Love"
new = ""

# 241 - Electrosaturator
[[translation]]
old = "Electrosaturator"
new = ""

# 242 - 1/6 -out of the gravity-
[[translation]]
old = "1/6 -out of the gravity-"
new = ""

# 243 - Interviewer
[[translation]]
old = "Interviewer"
new = ""

# 244 - Snowman
[[translation]]
old = "Snowman"
new = ""

# 246 - Terekakushi Shishunki
[[translation]]
old = "Terekakushi Shishunki"
new = ""

# 247 - Sweet Magic
[[translation]]
old = "Sweet Magic"
new = ""

# 248 - Arifureta Sekai Seifuku
[[translation]]
old = "Arifureta Sekai Seifuku"
new = ""

# 249 - Ageage Again
[[translation]]
old = "Ageage Again"
new = ""

# 250 - Nice To Meet You, Mr. Earthling
[[translation]]
old = "Nice To Meet You, Mr. Earthling"
new = ""

# 251 - PIANO*GIRL
[[translation]]
old = "PIANO*GIRL"
new = ""

# 253 - LOL -lots of laugh-
[[translation]]
old = "LOL -lots of laugh-"
new = ""

# 254 - Amatsu Kitsune
[[translation]]
old = "Amatsu Kitsune"
new = ""

# 255 - Gaikotsu Gakudan to Riria
[[translation]]
old = "Gaikotsu Gakudan to Riria"
new = ""

# 257 - shake it!
[[translation]]
old = "shake it!"
new = ""

# 259 - Cendrillon
[[translation]]
old = "Cendrillon"
new = ""

# 260 - Adolescence
[[translation]]
old = "Adolescence"
new = ""

# 261 - Kimi no Taion
[[translation]]
old = "Kimi no Taion"
new = ""

# 262 - Piano × Forte × Scandal
[[translation]]
old = "Piano × Forte × Scandal"
new = ""

# 263 - 1925
[[translation]]
old = "1925"
new = ""

# 265 - Hibikase
[[translation]]
old = "Hibikase"
new = ""

# 266 - Ghost Rule
[[translation]]
old = "Ghost Rule"
new = ""

# 267 - Suna no Wakusei feat. Hatsune Miku
[[translation]]
old = "Suna no Wakusei feat. Hatsune Miku"
new = ""

# 268 - Catch the Wave
[[translation]]
old = "Catch the Wave"
new = ""

# 269 - 39 Music!
[[translation]]
old = "39 Music!"
new = ""

# 270 - Alien Alien
[[translation]]
old = "Alien Alien"
new = ""

# 271 - Teo
[[translation]]
old = "Teo"
new = ""

# 272 - HIBANA
[[translation]]
old = "HIBANA"
new = ""

# 273 - ROKI
[[translation]]
old = "ROKI"
new = ""

# 274 - Jigsaw puzzle
[[translation]]
old = "Jigsaw puzzle"
new = ""

# 275 - Dreamin Chuchu
[[translation]]
old = "Dreamin Chuchu"
new = ""

# 276 - Ooedo Julianight
[[translation]]
old = "Ooedo Julianight"
new = ""

# 277 - JITTERBUG
[[translation]]
old = "JITTERBUG"
new = ""

# 278 - Bless Your Breath
[[translation]]
old = "Bless Your Breath"
new = ""

# 279 - BRING IT ON
[[translation]]
old = "BRING IT ON"
new = ""

# 280 - Dramaturgy
[[translation]]
old = "Dramaturgy"
new = ""

# 281 - Greenlights Serenade
[[translation]]
old = "Greenlights Serenade"
new = ""

# 433 - Paris Cinema Girl
[[translation]]
old = "Paris Cinema Girl"
new = ""

# 435 - Denparadigm
[[translation]]
old = "Denparadigm"
new = ""

# 600 - Cat Food
[[translation]]
old = "Cat Food"
new = ""

# 601 - Monochrome∞Blue Sky
[[translation]]
old = "Monochrome∞Blue Sky"
new = ""

# 602 - Fire◎Flower
[[translation]]
old = "Fire◎Flower"
new = ""

# 603 - DYE
[[translation]]
old = "DYE"
new = ""

# 604 - Torinokocity
[[translation]]
old = "Torinokocity"
new = ""

# 605 - Hm? Ah, Yes.
[[translation]]
old = "Hm? Ah, Yes."
new = ""

# 607 - Secret Police
[[translation]]
old = "Secret Police"
new = ""

# 608 - What Do You Mean!?
[[translation]]
old = "What Do You Mean!?"
new = ""

# 609 - God-Tier Tune
[[translation]]
old = "God-Tier Tune"
new = ""

# 610 - Nyanyanyanyanyanyanya!
[[translation]]
old = "Nyanyanyanyanyanyanya!"
new = ""

# 611 - ACUTE
[[translation]]
old = "ACUTE"
new = ""

# 612 - Time Machine
[[translation]]
old = "Time Machine"
new = ""

# 613 - Ashes to Ashes
[[translation]]
old = "Ashes to Ashes"
new = ""

# 614 - Glasses
[[translation]]
old = "Glasses"
new = ""

# 615 - Melancholic
[[translation]]
old = "Melancholic"
new = ""

# 616 - Unhappy Refrain
[[translation]]
old = "Unhappy Refrain"
new = ""

# 617 - The MMORPG Addict's Anthem
[[translation]]
old = "The MMORPG Addict's Anthem"
new = ""

# 619 - Tengaku
[[translation]]
old = "Tengaku"
new = ""

# 620 - Remote Controller
[[translation]]
old = "Remote Controller"
new = ""

# 621 - Nostalogic
[[translation]]
old = "Nostalogic"
new = ""

# 622 - Stay with me
[[translation]]
old = "Stay with me"
new = ""

# 623 - Sadistic.Music∞Factory
[[translation]]
old = "Sadistic.Music∞Factory"
new = ""

# 624 - Summer Idol
[[translation]]
old = "Summer Idol"
new = ""

# 625 - Odds & Ends
[[translation]]
old = "Odds & Ends"
new = ""

# 626 - Weekender Girl
[[translation]]
old = "Weekender Girl"
new = ""

# 627 - World's End Umbrella
[[translation]]
old = "World's End Umbrella"
new = ""

# 628 - Freely Tomorrow
[[translation]]
old = "Freely Tomorrow"
new = ""

# 629 - Negaposi＊Continues
[[translation]]
old = "Negaposi＊Continues"
new = ""

# 630 - Black★Rock Shooter
[[translation]]
old = "Black★Rock Shooter"
new = ""

# 631 - Continuing Dream
[[translation]]
old = "Continuing Dream"
new = ""

# 637 - Senbonzakura -F edition-
[[translation]]
old = "Senbonzakura -F edition-"
new = ""

# 638 - Tell Your World
[[translation]]
old = "Tell Your World"
new = ""

# 639 - Tokyo Teddy Bear
[[translation]]
old = "Tokyo Teddy Bear"
new = ""

# 640 - Dream-Eating Monochrome Baku
[[translation]]
old = "Dream-Eating Monochrome Baku"
new = ""

# 641 - Rin-chan Now!
[[translation]]
old = "Rin-chan Now!"
new = ""

# 642 - Sweet Devil
[[translation]]
old = "Sweet Devil"
new = ""

# 710 - Sakura no Ame
[[translation]]
old = "Sakura no Ame"
new = ""

# 722 - Meteor
[[translation]]
old = "Meteor"
new = ""

# 723 - 2D Dream Fever
[[translation]]
old = "2D Dream Fever"
new = ""

# 724 - Envy Cat Walk
[[translation]]
old = "Envy Cat Walk"
new = ""

# 725 - Pinky Swear
[[translation]]
old = "Pinky Swear"
new = ""

# 726 - Karakuri Pierrot
[[translation]]
old = "Karakuri Pierrot"
new = ""

# 727 - Love-Hate
[[translation]]
old = "Love-Hate"
new = ""

# 728 - Erase or Zero
[[translation]]
old = "Erase or Zero"
new = ""

# 729 - This is the Happiness and Peace of Mind Committee
[[translation]]
old = "This is the Happiness and Peace of Mind Committee"
new = ""

# 730 - Hello, Worker
[[translation]]
old = "Hello, Worker"
new = ""

# 731 - Knife
[[translation]]
old = "Knife"
new = ""

# 732 - Akatsuki Arrival
[[translation]]
old = "Akatsuki Arrival"
new = ""

# 733 - Doubleganger
[[translation]]
old = "Doubleganger"
new = ""

# 734 - Break It, Break It!
[[translation]]
old = "Break It, Break It!"
new = ""

# 736 - Two Breaths Walking
[[translation]]
old = "Two Breaths Walking"
new = ""

# 737 - Soundless Voice
[[translation]]
old = "Soundless Voice"
new = ""

# 738 - Blackjack
[[translation]]
old = "Blackjack"
new = ""

# 739 - Decorator
[[translation]]
old = "Decorator"
new = ""

# 740 - Glory 3usi9
[[translation]]
old = "Glory 3usi9"
new = ""

# 832 - Hand in Hand
[[translation]]
old = "Hand in Hand"
new = ""