# nswgam_custom
8 = "Not Set" # Acessórios Selecionados
9 = "Default Items" # Acessórios Selecionados
11 = "Not enough VP."
13 = "You cannot change the hairstyle\nfor this module."
34 = "Extra Characters"
45 = "You cannot change the hairstyle\nfor this module."
79 = "Some icons have not been configured."
84 = "Random Hairstyle"
85 = "Match Module"
87 = "Random Miku"
88 = "Random Rin"
89 = "Random Len"
90 = "Random Luka"
91 = "Random Neru"
92 = "Random Haku"
93 = "Random KAITO"
94 = "Random MEIKO"
95 = "Random S. Meiko"
96 = "Random Teto"
106 = "Song Defaults"
107 = "Button FX A"
108 = "Button FX B"
109 = "Button FX C"
110 = "Button FX D"
111 = "Button FX E"
112 = "Button FX F"
113 = "Button FX G"
114 = "Button FX H"
115 = "Button FX I"
116 = "Hi-hat A"
117 = "Hi-hat A (2nd)"
118 = "Hi-hat B"
119 = "Hi-hat B (2nd)"
120 = "Taiko Drum"
121 = "Taiko Drum (2nd)"
122 = "Woodblock A"
123 = "Woodblock A (2nd)"
124 = "Woodblock B"
125 = "Woodblock B (2nd)"
126 = "Stick"
127 = "Tambourine"
128 = "Tambourine (2nd)"
129 = "Bell"
130 = "Clap"
131 = "Chain Slide A"
132 = "Chain Slide B"
133 = "Chain Slide C"
134 = "Chain Slide D"
135 = "Chain Slide E"
136 = "Chain Slide F"
137 = "Chain Slide G"
138 = "Chain Slide H"
139 = "Chain Slide I"
140 = "Chain Slide J"
141 = "Chain Slide K"
142 = "Chain Slide L"
143 = "Chain Slide M"
144 = "Chain Slide N"
145 = "Chain Slide O"
146 = "Chain Slide P"
147 = "Chain Slide Q"
148 = "Chain Slide R"
149 = "Slide A"
150 = "Slide B"
151 = "Slide C"
152 = "Slide D"
153 = "Slide E"
154 = "Slide F"
155 = "Slide G"
156 = "Wind Chimes"
158 = "Button FX A"
159 = "Button FX B"
160 = "Button FX C"
161 = "Button FX D"
162 = "Button FX E"
163 = "Button FX F"
164 = "Slide A"
165 = "Slide B"
166 = "Slide C"
167 = "Slide D"
168 = "Slide E"
169 = "Slide F"
170 = "ON"
171 = "OFF"
174 = "ALL"
175 = "GREAT"
176 = "EXCELLENT"
177 = "Left"
178 = "Right"
179 = "Center"
192 = "Change sound, loading screens, and other settings."
193 = "Change button settings for melody/slide icon controls."
194 = "Change settings for supporting multi-melody icon actions."
195 = "Enable/Disable rumble feature on the Controller."
196 = "Set whether or not vocals are sung when you make an error during Rhythm Game."
197 = "Select one of thirteen styles for the melody icons displayed in Rhythm Game."
198 = "Set whether to display the GREAT and EXCELLENT clear thresholds on the clear gauge."
199 = "Follow the onscreen instructions to calibrate the timing for Rhythm Game."
200 = "Manually adjust the timing when melody icons overlap the target."
201 = "Enable/Disable assist options that increase your score while a button is held down."
202 = "Choose whether to display combos on the right, center, or left."
203 = "Adjust the cursor sensitivity. Higher values increase sensitivity." # Cursor > Joy-Con
205 = "Change loading screen backgrounds."
206 = "View the manual."
214 = "Set the Arcade Controller to ON or OFF, and calibrate the controller."
215 = "When the Arcade Controller is set to ON,\nthe Left Stick and Right Stick controls\nwill change to support the Touch Slider instead.\nThis can make normal controls difficult, so please\nonly enable this setting when using the Arcade Controller."
219 = "Turn Tap Play On/Off. Learn more about Tap Play in Help."
252 = "Up Melody Icon"
253 = "Left Melody Icon"
254 = "Down Melody Icon"
255 = "Right Melody Icon"
256 = "Left Slide Icon"
257 = "Right Slide Icon"
258 = "Multi-press Up+Left"
259 = "Multi-press Up+Down"
260 = "Multi-press Up+Right"
261 = "Multi-press Left+Down"
262 = "Multi-press Left+Right"
263 = "Multi-press Down+Right"
264 = "Multi-press Up+Left+Down"
265 = "Multi-press Up+Left+Right"
266 = "Multi-press Up+Down+Right"
267 = "Multi-press Left+Down+Right"
268 = "Multi-press Up+Left+Down+Right"
273 = "Be sure to set an input for each of the melody and slide icons."

# nswgam_gallery
66 = "A timeout error occurred."
67 = "An error occurred."
68 = "Posting to the rankings is not allowed."
69 = "Failed to obtain rankings."
70 = "Rankings are not available."
71 = "Updating Rankings..."
189 = "View stats such as your scores and completion level, as well as online rankings."
209 = "View statistics for details such as your scores and Clear %."
210 = "View high score and Clear % online rankings. Note this requires a network connection."
211 = "Play a tutorial that teaches you game basics. Note the tutorial uses default controls."
212 = "View Hatsune Miku: Project DIVA Mega Mix+ promo videos."
213 = "View the Credits. "
271 = "View license information."

# nswgam_game
39 = "There is not enough free space in the System Memory.\nFailed to save screenshot."
172 = "Enable" # Também é usado em outros lugares
173 = "Disable" # Também é usado em outros lugares

# nswgam_menu
185 = "Play the rhythm game or watch music videos."
186 = "Purchase and configure modules, hairstyles, and accessories, or change game & control settings."
187 = "Build and edit custom playlists to play your favorite music videos one after another."
188 = "View your scores and completion levels."
190 = "Connect to the Online Store."
191 = "Change sound settings and Autosave settings."

# nswgam_option
50 = "ON" # Também é usado no nswgam_songselector
51 = "OFF" # Também é usado no nswgam_songselector
204 = "Select your menu sound themes and adjust various sound levels."
207 = "ON/OFF Autosave."
208 = "Save the current game state."
216 = "Failed to save game."
220 = "Select which sound theme to play in menu and results screens."
221 = "Adjust music volume in menus and Rhythm Game."
222 = "Adjust sound FX volume when pressing buttons on rhythm icons."
223 = "Adjust volume of sound FX not related to Rhythm Game buttons."
224 = "Change screen settings like resolution."
225 = "Configure which display to use for the game screen."
226 = "Configure display mode to use for the game screen."
227 = "Configure the resolution of the game screen."
228 = "Configure the frame rate of the game screen."
229 = "Configure V-Sync settings."
230 = "Configure graphic quality by selecting a preset or adjusting individual settings."
231 = "Configure multiple graphic quality settings at once."
232 = "Set the scaling value for the screen resolution."
233 = "Toggle between different settings for smoothing out the edges of objects." # FXAA/MLAA
234 = "Toggle between blur processing for subjects other than the one in focus."
235 = "Set the quality of shadows."
236 = "Set the quality of the glow surrounding lights."
237 = "Set the quality of reflections."
238 = "Change a character's appearance." # É a opção de escolher entre o modo de renderização do Future Tone/Mega Mix. O jeito que está escrito parece meio vago
239 = "With Frame"
240 = "No Frame"
241 = "Full Screen"
242 = "Unlimited"
243 = "Lowest"
244 = "Low"
245 = "Mid"
246 = "High"
247 = "Highest"
248 = "Custom"
251 = "Default Audio Device"
272 = "Configure your audio device for sound playback."
274 = "Display%d"

# nswgam_playlist
100 = "Create New Playlist"
101 = "You've reached the maximum number of playlists allowed."
102 = "You've reached the maximum number of songs allowed in a playlist."
103 = "You've reached 100% capacity."
104 = "Rename"

# nswgam_result
41 = "You cleared the song on HARD difficulty!\n\nYou can now play this song on EXTREME difficulty!\nClearing HARD difficulty unlocks a new EXTREME\ndifficulty level for each song, and on certain\nsongs, an EXTRA EXTREME difficulty too!"
42 = "You cleared the song on HARD difficulty!\n\nYou can now play this song on EXTREME\nor EXTRA EXTREME difficulty!\nClearing HARD difficulty unlocks a new EXTREME\ndifficulty level for each song, and on certain\nsongs, an EXTRA EXTREME difficulty too!"
43 = "You cleared the song on NORMAL difficulty!\n\nYou can now play this song on HARD difficulty!\nClearing NORMAL difficulty unlocks a new HARD\ndifficulty level for each song!"
63 = "Failed to upload rankings.\n\nUploads to the rankings can occur any time the game is running.\nYou can change upload settings at any time under Rankings in the Gallery."

# nswgam_songselector
46 = "NONE"
47 = "HI SPEED"
48 = "HIDDEN"
49 = "SUDDEN"
52 = "N/A"
53 = "No Fail Mode"
54 = "Game Modifiers"
55 = "Change Vocals"
56 = "All Version" # Senbonzakura -F edition "All Version"-
59 = "Success Effects"
60 = "Change Video"
61 = "Start Time"
62 = "Note Speed"

# nswgam_tshirtsedit
217 = "Failed to save T-shirt edits."
218 = "Failed to save T-shirt edits.\nPlease free up space to create save data."

# ?
37 = "Unable to create save data.\nPlease free up space to create save data."
38 = "Save data is corrupted.\nPlease delete save data."
40 = "This game supports Autosave.\nDo not turn off the system while the following image is\ndisplayed.\nThis could cause save data to become corrupted.\n\nYou can turn Autosave ON/OFF under Options."
44 = "Autosave has been enabled.\n\nDo not turn off the system\nwhile the following image is displayed.\nThis could cause save data to become corrupted."
72 = "N/A"
81 = "An error occurred."
98 = "HARD"
180 = "Enable"
181 = "Disable"
182 = "Default + Vid Photos"
183 = "Video Photos"
184 = "Default"
249 = "【仮】デバイス状態検知"
250 = "Your controller has been disconnected.\nPlease reconnect it or connect another controller to continue."