# spr_nswgam_custom
170 = "LIGADO"
171 = "DESLIGADO"

# nswgam_menu
185 = "Play the rhythm game or watch music videos."
186 = "Purchase and configure modules, hairstyles, and accessories, or change game &amp; control settings."
187 = "Build and edit custom playlists to play your favorite music videos one after another." 
188 = "View your scores and completion levels."   
190 = "Connect to the Online Store."
191 = "Change sound settings and Autosave settings."

# nswgam_option
50 = "LIGADO" # Também é usado no nswgam_songselector
51 = "DESLIGADO" # Também é usado no nswgam_songselector
204 = "Select your menu sound themes and adjust various sound levels."
207 = "Autosave LIGADO/DESLIGADO"
208 = "Save the current game state."
220 = "Select which sound theme to play in menu and results screens."
221 = "Adjust music volume in menus and Rhythm Game."
222 = "Adjust sound FX volume when pressing buttons on rhythm icons."
223 = "Adjust volume of sound FX not related to Rhythm Game buttons."
224 = "Change screen settings like resolution."
225 = "Configure which display to use for the game screen."
226 = "Configure display mode to use for the game screen."
227 = "Configure the resolution of the game screen."
230 = "Configure graphic quality by selecting a preset or adjusting individual settings."
231 = "Configure multiple graphic quality settings at once."
232 = "Set the scaling value for the screen resolution."
233 = "Toggle between different settings for smoothing out the edges of objects." # FXAA/MLAA
235 = "Set the quality of shadows."
237 = "Set the quality of reflections."
238 = "Change a character's appearance." # É a opção de escolher entre o modo de renderização do Future Tone/Mega Mix. O jeito que está escrito parece meio vago
239 = "Janela"
240 = "Janela sem Borda"
241 = "Tela Cheia"
243 = "Mínima"
244 = "Baixa"
245 = "Média"
246 = "Alta"
247 = "Máxima" 
248 = "Customizada"
251 = "Dispositivo de Áudio Padrão"
272 = "Configure your audio device for sound playback."
274 = "Tela %d"

# nswgam_songselector
46 = "NENHUM"
47 = "RÁPIDO"
48 = "ESCONDIDO"
49 = "SÚBITO"
52 = "INDISPONÍVEL"
53 = "Modo Sem Falha"
54 = "Modificadores de Jogo"
55 = "Mudar Vocal"
59 = "Efeitos de Sucesso"
60 = "Mudar Vídeo"
61 = "Tempo de Início"

# ?
72 = "INDISPONÍVEL"
